import { index, route, type RouteConfig } from "@react-router/dev/routes";
export default [
  index("routes/home.tsx"),
  route("courses", "routes/courses.tsx"),
  route("lessons/:lessonId", "routes/lesson.tsx"),
  route("learning/:sessionId", "routes/learning.tsx"),
  route("practice/:lessonId", "routes/practice.tsx"),
  route("review/:lessonId", "routes/review.tsx"),
  route("reviews", "routes/reviews.tsx"),
  route("library", "routes/library.tsx"),
  route("review-history", "routes/review-history.tsx"),
  route("profile", "routes/profile.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/history", "routes/admin-history.tsx"),
  route("admin/accounts", "routes/admin-accounts.tsx"),
  route("admin/characters", "routes/admin-characters.tsx"),
  route("admin/assets", "routes/admin-assets.tsx"),
  route("admin/recordings", "routes/admin-recordings.tsx"),
  route("admin/voice-references", "routes/admin-voice-references.tsx"),
  route("admin/voice-jobs", "routes/admin-voice-jobs.tsx"),
  route("admin/voice-auditions", "routes/admin-voice-auditions.tsx"),
  route("admin/speech-plans", "routes/admin-speech-plans.tsx"),
  route("admin/speech-clips", "routes/admin-speech-clips.tsx"),
  route("admin/speech-alignments", "routes/admin-speech-alignments.tsx"),
  route("admin/tokens", "routes/admin-tokens.tsx"),
  route("admin/accounts/:accountId/sessions", "routes/admin-sessions.tsx"),
  route("author-preview", "routes/author-preview.tsx"),
  route("pending-saves", "routes/pending-saves.tsx"),
  route("login", "routes/login.tsx"),
  route("invite", "routes/invite.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("health", "routes/health.ts"),
] satisfies RouteConfig;
