use brioche_course_contract::{
    ApiError, Catalog, CsrfToken, GradeRequest, GradeResult, PublicLesson,
};
use std::{fs, path::Path};
use ts_rs::TS;
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let out = match args.as_slice() {
        [] => Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packages/contracts/src/generated"),
        [option, directory] if option == "--output" && !directory.is_empty() => {
            Path::new(directory).to_path_buf()
        }
        _ => return Err("Expected no arguments or --output <directory>".into()),
    };
    fs::create_dir_all(&out)?;
    fs::write(
        out.join("answer-limits.ts"),
        format!(
            "// Generated by brioche-course-contract; do not edit.\nexport const MAX_TEXT_ANSWER_UTF16_UNITS = {};\nexport const MAX_TEXT_ANSWER_BYTES = {};\n",
            brioche_course_contract::MAX_TEXT_ANSWER_UTF16_UNITS,
            brioche_course_contract::MAX_TEXT_ANSWER_BYTES,
        ),
    )?;
    fs::write(
        out.join("tts-voices.ts"),
        format!(
            "// Generated by brioche-course-contract; do not edit.\nexport const QWEN_FRENCH_SYSTEM_VOICES = {} as const;\n",
            serde_json::to_string(brioche_course_contract::QWEN_FRENCH_SYSTEM_VOICES)?
        ),
    )?;
    let config = ts_rs::Config::default().with_out_dir(&out);
    PublicLesson::export_all(&config)?;
    brioche_course_contract::ReadingText::export_all(&config)?;
    brioche_course_contract::TargetLanguage::export_all(&config)?;
    Catalog::export_all(&config)?;
    brioche_course_contract::AdminOverview::export_all(&config)?;
    brioche_course_contract::AdminLessonAudioReview::export_all(&config)?;
    brioche_course_contract::AdminDirectPublication::export_all(&config)?;
    brioche_course_contract::AdminLessonAudioStatus::export_all(&config)?;
    brioche_course_contract::AdminLessonCursor::export_all(&config)?;
    brioche_course_contract::AdminReviewRequest::export_all(&config)?;
    brioche_course_contract::AdminActivateRequest::export_all(&config)?;
    brioche_course_contract::AdminWithdrawRequest::export_all(&config)?;
    brioche_course_contract::AdminDocumentRequest::export_all(&config)?;
    brioche_course_contract::AdminImportResult::export_all(&config)?;
    brioche_course_contract::AdminDocumentCheck::export_all(&config)?;
    brioche_course_contract::AdminHistory::export_all(&config)?;
    brioche_course_contract::AdminAccounts::export_all(&config)?;
    brioche_course_contract::AdminTokenRequest::export_all(&config)?;
    brioche_course_contract::AdminTokenResult::export_all(&config)?;
    brioche_course_contract::AdminRoleRequest::export_all(&config)?;
    brioche_course_contract::AdminSessions::export_all(&config)?;
    brioche_course_contract::AdminRevokeSessionRequest::export_all(&config)?;
    brioche_course_contract::AdminRevokeSessionResult::export_all(&config)?;
    brioche_course_contract::AdminCharacterVoices::export_all(&config)?;
    brioche_course_contract::AdminCharacterVoiceRequest::export_all(&config)?;
    brioche_course_contract::AdminPendingTokens::export_all(&config)?;
    brioche_course_contract::AdminAssets::export_all(&config)?;
    brioche_course_contract::AdminAssetUpload::export_all(&config)?;
    brioche_course_contract::AdminCharacterRequest::export_all(&config)?;
    brioche_course_contract::AdminRecordings::export_all(&config)?;
    brioche_course_contract::AdminRecordingUpload::export_all(&config)?;
    brioche_course_contract::AdminReferenceGrantRequest::export_all(&config)?;
    brioche_course_contract::AdminReferenceGrants::export_all(&config)?;
    brioche_course_contract::AdminReferenceGrantResult::export_all(&config)?;
    brioche_course_contract::AdminVoiceJobRequest::export_all(&config)?;
    brioche_course_contract::AdminVoiceJobCheck::export_all(&config)?;
    brioche_course_contract::AdminVoiceJobs::export_all(&config)?;
    brioche_course_contract::AdminAuditionRequest::export_all(&config)?;
    brioche_course_contract::AdminAuditionReview::export_all(&config)?;
    brioche_course_contract::AdminAuditions::export_all(&config)?;
    brioche_course_contract::AdminSpeechPlanRequest::export_all(&config)?;
    brioche_course_contract::AdminSpeechPlans::export_all(&config)?;
    brioche_course_contract::AdminSpeechClipRequest::export_all(&config)?;
    brioche_course_contract::AdminSpeechClips::export_all(&config)?;
    brioche_course_contract::AdminSpeechClipReview::export_all(&config)?;
    brioche_course_contract::AdminAlignmentImport::export_all(&config)?;
    brioche_course_contract::AdminAlignment::export_all(&config)?;
    brioche_course_contract::AdminAlignments::export_all(&config)?;
    brioche_course_contract::AdminAlignmentReview::export_all(&config)?;
    brioche_course_contract::AdminSpeechOptions::export_all(&config)?;
    brioche_course_contract::AdminSpeechPackageRequest::export_all(&config)?;
    brioche_course_contract::AdminAutomaticSpeechPackageRequest::export_all(&config)?;
    brioche_course_contract::AdminSpeechPackageImport::export_all(&config)?;
    brioche_course_contract::AdminSpeechPackageResult::export_all(&config)?;
    brioche_course_contract::AdminSpeechPackageResults::export_all(&config)?;
    brioche_course_contract::AdminRevokeTokenRequest::export_all(&config)?;
    brioche_course_contract::PreviewRelease::export_all(&config)?;
    ApiError::export_all(&config)?;
    GradeRequest::export_all(&config)?;
    GradeResult::export_all(&config)?;
    CsrfToken::export_all(&config)?;
    brioche_course_contract::ReviewQueue::export_all(&config)?;
    brioche_course_contract::ReviewCardsPage::export_all(&config)?;
    brioche_course_contract::ReviewPreferenceRequest::export_all(&config)?;
    brioche_course_contract::ReviewEnrollmentRequest::export_all(&config)?;
    brioche_course_contract::SavedPage::export_all(&config)?;
    brioche_course_contract::SavedWriteRequest::export_all(&config)?;
    brioche_course_contract::ReviewHistoryPage::export_all(&config)?;
    brioche_course_contract::ReviewAttemptRequest::export_all(&config)?;
    brioche_course_contract::ReviewAttemptResult::export_all(&config)?;
    brioche_course_contract::StartLearningRequest::export_all(&config)?;
    brioche_course_contract::LearningWriteRequest::export_all(&config)?;
    brioche_course_contract::SubmitAttemptRequest::export_all(&config)?;
    brioche_course_contract::LearningSession::export_all(&config)?;
    brioche_course_contract::AttemptResult::export_all(&config)?;
    brioche_course_contract::HintResult::export_all(&config)?;
    brioche_course_contract::LearningOverview::export_all(&config)?;
    brioche_course_contract::StudyDashboard::export_all(&config)?;
    brioche_course_contract::UserProfile::export_all(&config)?;
    brioche_course_contract::AccountProfile::export_all(&config)?;
    brioche_course_contract::AccountProfileUpdateRequest::export_all(&config)?;
    brioche_course_contract::AccountAuthResult::export_all(&config)?;
    brioche_course_contract::UpdateProfileRequest::export_all(&config)?;
    brioche_course_contract::AuthResult::export_all(&config)?;
    brioche_course_contract::LoginRequest::export_all(&config)?;
    brioche_course_contract::AcceptInviteRequest::export_all(&config)?;
    brioche_course_contract::ResetPasswordRequest::export_all(&config)?;
    fs::write(
        out.join("public-lesson.schema.json"),
        serde_json::to_string_pretty(&schemars::schema_for!(PublicLesson))?,
    )?;
    fs::write(
        out.join("reading-text.schema.json"),
        serde_json::to_string_pretty(&schemars::schema_for!(brioche_course_contract::ReadingText))?,
    )?;
    Ok(())
}
